version: "3.7"

services:
  cteleport-airports-service-api:
    image: cteleport-airports-service-api:latest
    build:
      dockerfile: Dockerfile
      context: ./
    environment:
      - REDIS_DSN=redis:6379
      - PLACES_API_CLIENT_BASE_URL=https://places-dev.cteleport.com/
    ports:
      - 5000:80
    networks:
      - cteleport-network
    depends_on:
      - redis

  redis:
    image: redis:6.0-alpine
    networks:
      - cteleport-network

networks:
  cteleport-network: